BASEROOTDIR="/mesap"
HISAT2 = "/usr/bin/hisat2"
STRINGTIE = "/usr/bin/stringtie"
SAMTOOLS = "/usr/bin/samtools"
CHECKBAM = "$BASEROOTDIR"+ "/scripts/check_bam_files.sh"
GLUE_4_BALLGOWN = "$BASEROOTDIR"+ "/pipelines/make_ballgown_obj.sh"
